web:
  build: docker/local/web
  ports:
    - 7000:80
  volumes:
    - .:/project
  links:
    - mysql:mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: q4f8zae94a89
    MYSQL_USER: drupal
    MYSQL_PASSWORD: vq<sd78q4fd89
    MYSQL_DATABASE: drupal
  volumes:
    - ./docker/local/mysql/data:/var/lib/mysql
