version: "2"
services:
  web:
    image: lune/dev-drupal
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: Eingeu4u
      MYSQL_DATABASE: drupal
      DRUPAL_URI: http://172.17.0.1:7000
    ports:
      - 7000:80
    volumes:
      - .:/project
      - ./etc/docker-compose/php-opcache-bug.ini:/usr/local/etc/php/conf.d/php-opcache-bug.ini:ro
      - ./etc/docker-compose/php-upload-size.ini:/usr/local/etc/php/conf.d/php-upload-size.ini:ro
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: aevei0Oh
      MYSQL_USER: admin
      MYSQL_PASSWORD: Eingeu4u
      MYSQL_DATABASE: drupal
    volumes:
      - ./var/docker-compose/mysql/data:/var/lib/mysql
